#!/bin/bash

set -xe

DOCKER=$(which docker)
if [[ -z $DOCKER ]]; then
  echo "No docker found in this environment"
  exit 1
fi

mkdir -p images

$DOCKER run \
  -v $PWD:/srcdir \
  -v $PWD/images:/artifact \
  --priviledge \
  archlinux:latest \
  bash -lc "
  ./install-deps.sh
  ./build-opensbi.sh cross-compile
  ./build-u-boot.sh cross-compile
  echo 'ALL ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
  git clone https://aur.archlinux.org/devtools-riscv64.git
  cd devtools-riscv64
  chown -R nobody $PWD
  sudo -u nobody makepkg -si --noconfirm
  ./mk-image.sh cross-compile
  mv image-$(date --rfc-3339=date).raw /artifact/
"

ls -al $PWD/images
