#!/bin/bash

set -xe

DOCKER=$(which docker)
if [[ -z $DOCKER ]]; then
  echo "No docker found in this environment"
  exit 1
fi

mkdir -p images

$DOCKER run \
  -v $PWD:/srcdir \
  -v $PWD/images:/artifact \
  --privileged \
  archlinux:latest \
  bash -lc '
  cd /srcdir
  ./install-deps.sh
  ./build-opensbi.sh cross-compile
  ./build-u-boot.sh cross-compile
  ./mk-image.sh cross-compile
  mv image-$(date --rfc-3339=date).raw /artifact/
'

ls -al $PWD/images
