#!/bin/bash

set -xe

DOCKER=$(which docker)
if [[ -z $DOCKER ]]; then
  echo "No docker found in this environment"
  exit 1
fi

mkdir -p images

$DOCKER run \
  -v $PWD:/srcdir \
  -v $PWD/images:/artifact \
  --privileged \
  archlinux:latest \
  bash -lc '
  cd /srcdir
  ./install-deps.sh
  git config --global --add safe.directory /srcdir
  git submodule update --init
  ./build-opensbi.sh cross-compile
  ./build-u-boot.sh cross-compile
  echo "ALL ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
  git clone https://aur.archlinux.org/devtools-riscv64.git
  pushd devtools-riscv64
  chown -R nobody $PWD
  sudo -u nobody makepkg -si --noconfirm
  popd
  ./mk-image.sh cross-compile
  mv image-$(date --rfc-3339=date).raw /artifact/
'

ls -al $PWD/images
