name: bootloader-builder
on:
  push:
    branches:
      - master
      - ci

jobs:
  bootloader-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup rv64 binfmt
        uses: docker/setup-qemu-action@v2
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build Image
        run: ./mkin-docker
      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: unmatched-bootloader-image
          path: ${{ github.workspace }}/images/arch-linux-*.img
